### ISSUE TITLE
 TypeError: ctx.sls.service.package.include.push is not a function

### ISSUE THREAD

**Issue by yasahmed** [prisma-labs/serverless-plugin-typescript#191]
im using typescriot for serverless framework so when i try to run serverless deploy i got this error:

 Type Error ---------------------------------------------
 
  TypeError: ctx.sls.service.package.include.push is not a function
      at /usr/local/lib/node_modules/serverless/node_modules/@serverless/lib/wrap.js:235:37
      at Generator.next (<anonymous>)
      at asyncGeneratorStep (/usr/local/lib/node_modules/serverless/node_modules/@serverless/enterprise-plugin/lib/wrap.js:8:103)
      at _next (/usr/local/lib/node_modules/serverless/node_modules/@serverless/enterprise-plugin/lib/wrap.js:10:194)
      at /usr/local/lib/node_modules/serverless/node_modules/@serverless/enterprise-plugin/lib/wrap.js:10:364
      at new Promise (<anonymous>)
      at /usr/local/lib/node_modules/serverless/node_modules/@serverless/enterprise-plugin/lib/wrap.js:10:97
      at wrap (/usr/local/lib/node_modules/serverless/node_modules/@serverless/lib/wrap.js:81:11)
      at ServerlessEnterprisePlugin.<anonymous> (/usr/local/lib/node_modules/serverless/node_modules/@serverless/lib/plugin.js:255:17)
      at Generator.next (<anonymous>)
      at asyncGeneratorStep (/usr/local/lib/node_modules/serverless/node_modules/@serverless/enterprise-plugin/lib/plugin.js:3:103)
      at _next (/usr/local/lib/node_modules/serverless/node_modules/@serverless/enterprise-plugin/lib/plugin.js:5:194)
      at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by KingDarBoja** [comment]
The error is not related to this plugin, please open a ticket at [enterprise-plugin](https://github.com/serverless/enterprise-plugin).
