### ISSUE TITLE
SyntaxError: Assigning to rvalue

### ISSUE THREAD

**Issue by vicary** [prisma-labs/serverless-plugin-typescript#207]
After a recent upgrade of the serverless package, there is a syntax error in the generated `.build/serverless_sdk/index.js`.

Bash output attached below.

```
SyntaxError: Assigning to rvalue (1:35618) while parsing /.../.build/serverless_sdk/index.js while parsing file: /.../.build/serverless_sdk/index.js
      at DestroyableTransform.end [as _flush] (/.../node_modules/insert-module-globals/index.js:114:21)
      at DestroyableTransform.prefinish (/.../node_modules/readable-stream/lib/_stream_transform.js:138:10)
      at DestroyableTransform.emit (events.js:210:5)
      at DestroyableTransform.EventEmitter.emit (domain.js:475:20)
      at prefinish (/.../node_modules/readable-stream/lib/_stream_writable.js:619:14)
      at finishMaybe (/.../node_modules/readable-stream/lib/_stream_writable.js:627:5)
      at endWritable (/.../node_modules/readable-stream/lib/_stream_writable.js:638:3)
      at DestroyableTransform.Writable.end (/.../node_modules/readable-stream/lib/_stream_writable.js:594:41)
      at BabelifyStream.onend (_stream_readable.js:692:10)
      at Object.onceWrapper (events.js:299:28)
      at BabelifyStream.emit (events.js:210:5)
      at BabelifyStream.EventEmitter.emit (domain.js:475:20)
      at endReadableNT (_stream_readable.js:1184:12)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)
```

Not sure where went wrong.

**Comment by vicary** [comment]
Fixed by deleting the `node_module` directory and install everything again, must be some kind of upgrade artifacts.

**Comment by vicary** [comment]
This is actually a bug caused by `serverless-plugin-optimize`, see https://github.com/FidelLimited/serverless-plugin-optimize/issues/97#issuecomment-642589749 for workaround.
